// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4sY2p4cNuq-zdi-KCjW9ekPYR-f1zJlQ',
    appId: '1:328223965531:web:faa93d5f8790f6d4a49a7e',
    messagingSenderId: '328223965531',
    projectId: 'tadish-57c14',
    authDomain: 'tadish-57c14.firebaseapp.com',
    storageBucket: 'tadish-57c14.appspot.com',
    measurementId: 'G-21S1FVF8WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuxyC_aJFbqiDyqjL1zbTXl8HmXwisktg',
    appId: '1:328223965531:android:073c8a2033ad4687a49a7e',
    messagingSenderId: '328223965531',
    projectId: 'tadish-57c14',
    storageBucket: 'tadish-57c14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC3oze59XiGj99gLMjbH_E2NIJFzfq3oY',
    appId: '1:328223965531:ios:9c5b98c27d653f61a49a7e',
    messagingSenderId: '328223965531',
    projectId: 'tadish-57c14',
    storageBucket: 'tadish-57c14.appspot.com',
    iosBundleId: 'com.example.tadish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC3oze59XiGj99gLMjbH_E2NIJFzfq3oY',
    appId: '1:328223965531:ios:0f0efc69d3d97d57a49a7e',
    messagingSenderId: '328223965531',
    projectId: 'tadish-57c14',
    storageBucket: 'tadish-57c14.appspot.com',
    iosBundleId: 'com.example.tadish.RunnerTests',
  );
}
